/* generated by genfwd.py — host gates forwarding to Wine */

static void g_k32_FindFirstFileA(CPUAlpha*c){ R(c,(uint64_t)(long long)FindFirstFileA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_FindNextFileA(CPUAlpha*c){ R(c,(uint64_t)(long long)FindNextFileA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_FindClose(CPUAlpha*c){ R(c,(uint64_t)(long long)FindClose((void*)(uintptr_t)A(c,0))); }
static void g_k32_GetFullPathNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFullPathNameA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_k32_GetFileAttributesA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFileAttributesA((void*)(uintptr_t)A(c,0))); }
static void g_k32_CreateFileA(CPUAlpha*c){ R(c,(uint64_t)(long long)CreateFileA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (unsigned)A(c,2), (void*)(uintptr_t)A(c,3), (unsigned)A(c,4), (unsigned)A(c,5), (void*)(uintptr_t)A(c,6))); }
static void g_k32_ReadFile(CPUAlpha*c){ R(c,(uint64_t)(long long)ReadFile((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4))); }
static void g_k32_SetFilePointer(CPUAlpha*c){ R(c,(uint64_t)(long long)SetFilePointer((void*)(uintptr_t)A(c,0), (int)A(c,1), (void*)(uintptr_t)A(c,2), (unsigned)A(c,3))); }
static void g_k32_GetFileSize(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFileSize((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_CloseHandle(CPUAlpha*c){ R(c,(uint64_t)(long long)CloseHandle((void*)(uintptr_t)A(c,0))); }
static void g_k32_CreateFileMappingA(CPUAlpha*c){ R(c,(uint64_t)(long long)CreateFileMappingA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (unsigned)A(c,3), (unsigned)A(c,4), (void*)(uintptr_t)A(c,5))); }
static void g_k32_MapViewOfFile(CPUAlpha*c){ R(c,(uint64_t)(long long)MapViewOfFile((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (unsigned)A(c,2), (unsigned)A(c,3), (unsigned)A(c,4))); }
static void g_k32_UnmapViewOfFile(CPUAlpha*c){ R(c,(uint64_t)(long long)UnmapViewOfFile((void*)(uintptr_t)A(c,0))); }
static void g_k32_GetFileInformationByHandle(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFileInformationByHandle((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_GetFileType(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFileType((void*)(uintptr_t)A(c,0))); }
static void g_k32_DeleteFileA(CPUAlpha*c){ R(c,(uint64_t)(long long)DeleteFileA((void*)(uintptr_t)A(c,0))); }
static void g_k32_GetTempPathA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetTempPathA((unsigned)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_GetShortPathNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetShortPathNameA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2))); }
static void g_k32_GetWindowsDirectoryA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetWindowsDirectoryA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1))); }
static void g_k32_GetSystemDirectoryA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetSystemDirectoryA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1))); }
static void g_k32_ExpandEnvironmentStringsA(CPUAlpha*c){ R(c,(uint64_t)(long long)ExpandEnvironmentStringsA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2))); }
static void g_k32_GetDriveTypeA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetDriveTypeA((void*)(uintptr_t)A(c,0))); }
static void g_k32_GetLogicalDrives(CPUAlpha*c){ R(c,(uint64_t)(long long)GetLogicalDrives()); }
static void g_k32_GlobalAlloc(CPUAlpha*c){ R(c,(uint64_t)(long long)GlobalAlloc((unsigned)A(c,0), (unsigned)A(c,1))); }
static void g_k32_GlobalLock(CPUAlpha*c){ R(c,(uint64_t)(long long)GlobalLock((void*)(uintptr_t)A(c,0))); }
static void g_k32_GlobalUnlock(CPUAlpha*c){ R(c,(uint64_t)(long long)GlobalUnlock((void*)(uintptr_t)A(c,0))); }
static void g_k32_LocalFree(CPUAlpha*c){ R(c,(uint64_t)(long long)LocalFree((void*)(uintptr_t)A(c,0))); }
static void g_k32_GetSystemTimeAsFileTime(CPUAlpha*c){ GetSystemTimeAsFileTime((void*)(uintptr_t)A(c,0)); R(c,0); }
static void g_k32_FileTimeToLocalFileTime(CPUAlpha*c){ R(c,(uint64_t)(long long)FileTimeToLocalFileTime((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_FileTimeToSystemTime(CPUAlpha*c){ R(c,(uint64_t)(long long)FileTimeToSystemTime((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_CompareFileTime(CPUAlpha*c){ R(c,(uint64_t)(long long)CompareFileTime((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_k32_GetDateFormatA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetDateFormatA((unsigned)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4), (int)A(c,5))); }
static void g_k32_GetTimeFormatA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetTimeFormatA((unsigned)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4), (int)A(c,5))); }
static void g_k32_FormatMessageA(CPUAlpha*c){ R(c,(uint64_t)(long long)FormatMessageA((unsigned)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (unsigned)A(c,3), (void*)(uintptr_t)A(c,4), (unsigned)A(c,5), (void*)(uintptr_t)A(c,6))); }
static void g_k32_GetLocaleInfoA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetLocaleInfoA((unsigned)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (int)A(c,3))); }
static void g_k32_GlobalMemoryStatus(CPUAlpha*c){ GlobalMemoryStatus((void*)(uintptr_t)A(c,0)); R(c,0); }
static void g_k32_GetComputerNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetComputerNameA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_adv_RegOpenKeyA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegOpenKeyA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (void*)(uintptr_t)A(c,2))); }
static void g_adv_RegOpenKeyExA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegOpenKeyExA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (unsigned)A(c,3), (void*)(uintptr_t)A(c,4))); }
static void g_adv_RegCloseKey(CPUAlpha*c){ R(c,(uint64_t)(long long)RegCloseKey((void*)(uintptr_t)A(c,0))); }
static void g_adv_RegQueryValueA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegQueryValueA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_adv_RegQueryValueExA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegQueryValueExA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4), (void*)(uintptr_t)A(c,5))); }
static void g_adv_RegSetValueA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegSetValueA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (void*)(uintptr_t)A(c,3), (int)A(c,4))); }
static void g_adv_RegEnumKeyA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegEnumKeyA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (unsigned)A(c,3))); }
static void g_adv_RegEnumValueA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegEnumValueA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4), (void*)(uintptr_t)A(c,5), (void*)(uintptr_t)A(c,6), (void*)(uintptr_t)A(c,7))); }
static void g_adv_RegDeleteKeyA(CPUAlpha*c){ R(c,(uint64_t)(long long)RegDeleteKeyA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_adv_GetUserNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetUserNameA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_shl_ShellExecuteA(CPUAlpha*c){ R(c,(uint64_t)(long long)ShellExecuteA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (void*)(uintptr_t)A(c,2), (void*)(uintptr_t)A(c,3), (void*)(uintptr_t)A(c,4), (int)A(c,5))); }
static void g_shl_ShellExecuteExA(CPUAlpha*c){ R(c,(uint64_t)(long long)ShellExecuteExA((void*)(uintptr_t)A(c,0))); }
static void g_shl_SHGetPathFromIDListA(CPUAlpha*c){ R(c,(uint64_t)(long long)SHGetPathFromIDListA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_shl_SHBrowseForFolderA(CPUAlpha*c){ R(c,(uint64_t)(long long)SHBrowseForFolderA((void*)(uintptr_t)A(c,0))); }
static void g_shl_SHGetMalloc(CPUAlpha*c){ R(c,(uint64_t)(long long)SHGetMalloc((void*)(uintptr_t)A(c,0))); }
static void g_cdg_GetOpenFileNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetOpenFileNameA((void*)(uintptr_t)A(c,0))); }
static void g_cdg_GetSaveFileNameA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetSaveFileNameA((void*)(uintptr_t)A(c,0))); }
static void g_cdg_CommDlgExtendedError(CPUAlpha*c){ R(c,(uint64_t)(long long)CommDlgExtendedError()); }
static void g_cc_ImageList_Draw(CPUAlpha*c){ R(c,(uint64_t)(long long)ImageList_Draw((void*)(uintptr_t)A(c,0), (int)A(c,1), (void*)(uintptr_t)A(c,2), (int)A(c,3), (int)A(c,4), (unsigned)A(c,5))); }
static void g_cc_InitCommonControls(CPUAlpha*c){ InitCommonControls(); R(c,0); }
static void g_gu2_CloseClipboard(CPUAlpha*c){ R(c,(uint64_t)(long long)CloseClipboard()); }
static void g_gu2_CopyRect(CPUAlpha*c){ R(c,(uint64_t)(long long)CopyRect((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_DrawFocusRect(CPUAlpha*c){ R(c,(uint64_t)(long long)DrawFocusRect((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_EmptyClipboard(CPUAlpha*c){ R(c,(uint64_t)(long long)EmptyClipboard()); }
static void g_gu2_EnableMenuItem(CPUAlpha*c){ R(c,(uint64_t)(long long)EnableMenuItem((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (unsigned)A(c,2))); }
static void g_gu2_EnableWindow(CPUAlpha*c){ R(c,(uint64_t)(long long)EnableWindow((void*)(uintptr_t)A(c,0), (int)A(c,1))); }
static void g_gu2_GetDC(CPUAlpha*c){ R(c,(uint64_t)(long long)GetDC((void*)(uintptr_t)A(c,0))); }
static void g_gu2_GetDlgItem(CPUAlpha*c){ R(c,(uint64_t)(long long)GetDlgItem((void*)(uintptr_t)A(c,0), (int)A(c,1))); }
static void g_gu2_GetFocus(CPUAlpha*c){ R(c,(uint64_t)(long long)GetFocus()); }
static void g_gu2_GetMessagePos(CPUAlpha*c){ R(c,(uint64_t)(long long)GetMessagePos()); }
static void g_gu2_GetMessageTime(CPUAlpha*c){ R(c,(uint64_t)(long long)GetMessageTime()); }
static void g_gu2_GetParent(CPUAlpha*c){ R(c,(uint64_t)(long long)GetParent((void*)(uintptr_t)A(c,0))); }
static void g_gu2_GetSubMenu(CPUAlpha*c){ R(c,(uint64_t)(long long)GetSubMenu((void*)(uintptr_t)A(c,0), (int)A(c,1))); }
static void g_gu2_GetSysColor(CPUAlpha*c){ R(c,(uint64_t)(long long)GetSysColor((int)A(c,0))); }
static void g_gu2_GetWindowRect(CPUAlpha*c){ R(c,(uint64_t)(long long)GetWindowRect((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_GetWindowTextA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetWindowTextA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (int)A(c,2))); }
static void g_gu2_GetWindowTextLengthA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetWindowTextLengthA((void*)(uintptr_t)A(c,0))); }
static void g_gu2_IsIconic(CPUAlpha*c){ R(c,(uint64_t)(long long)IsIconic((void*)(uintptr_t)A(c,0))); }
static void g_gu2_IsWindow(CPUAlpha*c){ R(c,(uint64_t)(long long)IsWindow((void*)(uintptr_t)A(c,0))); }
static void g_gu2_IsWindowEnabled(CPUAlpha*c){ R(c,(uint64_t)(long long)IsWindowEnabled((void*)(uintptr_t)A(c,0))); }
static void g_gu2_IsZoomed(CPUAlpha*c){ R(c,(uint64_t)(long long)IsZoomed((void*)(uintptr_t)A(c,0))); }
static void g_gu2_MessageBeep(CPUAlpha*c){ R(c,(uint64_t)(long long)MessageBeep((unsigned)A(c,0))); }
static void g_gu2_OpenClipboard(CPUAlpha*c){ R(c,(uint64_t)(long long)OpenClipboard((void*)(uintptr_t)A(c,0))); }
static void g_gu2_ReleaseDC(CPUAlpha*c){ R(c,(uint64_t)(long long)ReleaseDC((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_RemoveMenu(CPUAlpha*c){ R(c,(uint64_t)(long long)RemoveMenu((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (unsigned)A(c,2))); }
static void g_gu2_ScreenToClient(CPUAlpha*c){ R(c,(uint64_t)(long long)ScreenToClient((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_SetClipboardData(CPUAlpha*c){ R(c,(uint64_t)(long long)SetClipboardData((unsigned)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_SetFocus(CPUAlpha*c){ R(c,(uint64_t)(long long)SetFocus((void*)(uintptr_t)A(c,0))); }
static void g_gu2_DrawMenuBar(CPUAlpha*c){ R(c,(uint64_t)(long long)DrawMenuBar((void*)(uintptr_t)A(c,0))); }
static void g_gu2_SetMenu(CPUAlpha*c){ R(c,(uint64_t)(long long)SetMenu((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1))); }
static void g_gu2_GetMenu(CPUAlpha*c){ R(c,(uint64_t)(long long)GetMenu((void*)(uintptr_t)A(c,0))); }
static void g_gu2_WinHelpA(CPUAlpha*c){ R(c,(uint64_t)(long long)WinHelpA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (unsigned)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_gd2_CreateFontIndirectA(CPUAlpha*c){ R(c,(uint64_t)(long long)CreateFontIndirectA((void*)(uintptr_t)A(c,0))); }
static void g_gd2_ExtTextOutA(CPUAlpha*c){ R(c,(uint64_t)(long long)ExtTextOutA((void*)(uintptr_t)A(c,0), (int)A(c,1), (int)A(c,2), (unsigned)A(c,3), (void*)(uintptr_t)A(c,4), (void*)(uintptr_t)A(c,5), (unsigned)A(c,6), (void*)(uintptr_t)A(c,7))); }
static void g_gd2_GetCharWidthA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetCharWidthA((void*)(uintptr_t)A(c,0), (unsigned)A(c,1), (unsigned)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_gd2_GetObjectA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetObjectA((void*)(uintptr_t)A(c,0), (int)A(c,1), (void*)(uintptr_t)A(c,2))); }
static void g_gd2_GetTextAlign(CPUAlpha*c){ R(c,(uint64_t)(long long)GetTextAlign((void*)(uintptr_t)A(c,0))); }
static void g_gd2_GetTextExtentPoint32A(CPUAlpha*c){ R(c,(uint64_t)(long long)GetTextExtentPoint32A((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (int)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_gd2_GetTextExtentPointA(CPUAlpha*c){ R(c,(uint64_t)(long long)GetTextExtentPointA((void*)(uintptr_t)A(c,0), (void*)(uintptr_t)A(c,1), (int)A(c,2), (void*)(uintptr_t)A(c,3))); }
static void g_gd2_SetTextAlign(CPUAlpha*c){ R(c,(uint64_t)(long long)SetTextAlign((void*)(uintptr_t)A(c,0), (unsigned)A(c,1))); }

#define GENERATED_FORWARDERS \
    {"__k32_FindFirstFileA",g_k32_FindFirstFileA}, \
    {"__k32_FindNextFileA",g_k32_FindNextFileA}, \
    {"__k32_FindClose",g_k32_FindClose}, \
    {"__k32_GetFullPathNameA",g_k32_GetFullPathNameA}, \
    {"__k32_GetFileAttributesA",g_k32_GetFileAttributesA}, \
    {"__k32_CreateFileA",g_k32_CreateFileA}, \
    {"__k32_ReadFile",g_k32_ReadFile}, \
    {"__k32_SetFilePointer",g_k32_SetFilePointer}, \
    {"__k32_GetFileSize",g_k32_GetFileSize}, \
    {"__k32_CloseHandle",g_k32_CloseHandle}, \
    {"__k32_CreateFileMappingA",g_k32_CreateFileMappingA}, \
    {"__k32_MapViewOfFile",g_k32_MapViewOfFile}, \
    {"__k32_UnmapViewOfFile",g_k32_UnmapViewOfFile}, \
    {"__k32_GetFileInformationByHandle",g_k32_GetFileInformationByHandle}, \
    {"__k32_GetFileType",g_k32_GetFileType}, \
    {"__k32_DeleteFileA",g_k32_DeleteFileA}, \
    {"__k32_GetTempPathA",g_k32_GetTempPathA}, \
    {"__k32_GetShortPathNameA",g_k32_GetShortPathNameA}, \
    {"__k32_GetWindowsDirectoryA",g_k32_GetWindowsDirectoryA}, \
    {"__k32_GetSystemDirectoryA",g_k32_GetSystemDirectoryA}, \
    {"__k32_ExpandEnvironmentStringsA",g_k32_ExpandEnvironmentStringsA}, \
    {"__k32_GetDriveTypeA",g_k32_GetDriveTypeA}, \
    {"__k32_GetLogicalDrives",g_k32_GetLogicalDrives}, \
    {"__k32_GlobalAlloc",g_k32_GlobalAlloc}, \
    {"__k32_GlobalLock",g_k32_GlobalLock}, \
    {"__k32_GlobalUnlock",g_k32_GlobalUnlock}, \
    {"__k32_LocalFree",g_k32_LocalFree}, \
    {"__k32_GetSystemTimeAsFileTime",g_k32_GetSystemTimeAsFileTime}, \
    {"__k32_FileTimeToLocalFileTime",g_k32_FileTimeToLocalFileTime}, \
    {"__k32_FileTimeToSystemTime",g_k32_FileTimeToSystemTime}, \
    {"__k32_CompareFileTime",g_k32_CompareFileTime}, \
    {"__k32_GetDateFormatA",g_k32_GetDateFormatA}, \
    {"__k32_GetTimeFormatA",g_k32_GetTimeFormatA}, \
    {"__k32_FormatMessageA",g_k32_FormatMessageA}, \
    {"__k32_GetLocaleInfoA",g_k32_GetLocaleInfoA}, \
    {"__k32_GlobalMemoryStatus",g_k32_GlobalMemoryStatus}, \
    {"__k32_GetComputerNameA",g_k32_GetComputerNameA}, \
    {"__adv_RegOpenKeyA",g_adv_RegOpenKeyA}, \
    {"__adv_RegOpenKeyExA",g_adv_RegOpenKeyExA}, \
    {"__adv_RegCloseKey",g_adv_RegCloseKey}, \
    {"__adv_RegQueryValueA",g_adv_RegQueryValueA}, \
    {"__adv_RegQueryValueExA",g_adv_RegQueryValueExA}, \
    {"__adv_RegSetValueA",g_adv_RegSetValueA}, \
    {"__adv_RegEnumKeyA",g_adv_RegEnumKeyA}, \
    {"__adv_RegEnumValueA",g_adv_RegEnumValueA}, \
    {"__adv_RegDeleteKeyA",g_adv_RegDeleteKeyA}, \
    {"__adv_GetUserNameA",g_adv_GetUserNameA}, \
    {"__shl_ShellExecuteA",g_shl_ShellExecuteA}, \
    {"__shl_ShellExecuteExA",g_shl_ShellExecuteExA}, \
    {"__shl_SHGetPathFromIDListA",g_shl_SHGetPathFromIDListA}, \
    {"__shl_SHBrowseForFolderA",g_shl_SHBrowseForFolderA}, \
    {"__shl_SHGetMalloc",g_shl_SHGetMalloc}, \
    {"__cdg_GetOpenFileNameA",g_cdg_GetOpenFileNameA}, \
    {"__cdg_GetSaveFileNameA",g_cdg_GetSaveFileNameA}, \
    {"__cdg_CommDlgExtendedError",g_cdg_CommDlgExtendedError}, \
    {"__cc_ImageList_Draw",g_cc_ImageList_Draw}, \
    {"__cc_InitCommonControls",g_cc_InitCommonControls}, \
    {"__gu2_CloseClipboard",g_gu2_CloseClipboard}, \
    {"__gu2_CopyRect",g_gu2_CopyRect}, \
    {"__gu2_DrawFocusRect",g_gu2_DrawFocusRect}, \
    {"__gu2_EmptyClipboard",g_gu2_EmptyClipboard}, \
    {"__gu2_EnableMenuItem",g_gu2_EnableMenuItem}, \
    {"__gu2_EnableWindow",g_gu2_EnableWindow}, \
    {"__gu2_GetDC",g_gu2_GetDC}, \
    {"__gu2_GetDlgItem",g_gu2_GetDlgItem}, \
    {"__gu2_GetFocus",g_gu2_GetFocus}, \
    {"__gu2_GetMessagePos",g_gu2_GetMessagePos}, \
    {"__gu2_GetMessageTime",g_gu2_GetMessageTime}, \
    {"__gu2_GetParent",g_gu2_GetParent}, \
    {"__gu2_GetSubMenu",g_gu2_GetSubMenu}, \
    {"__gu2_GetSysColor",g_gu2_GetSysColor}, \
    {"__gu2_GetWindowRect",g_gu2_GetWindowRect}, \
    {"__gu2_GetWindowTextA",g_gu2_GetWindowTextA}, \
    {"__gu2_GetWindowTextLengthA",g_gu2_GetWindowTextLengthA}, \
    {"__gu2_IsIconic",g_gu2_IsIconic}, \
    {"__gu2_IsWindow",g_gu2_IsWindow}, \
    {"__gu2_IsWindowEnabled",g_gu2_IsWindowEnabled}, \
    {"__gu2_IsZoomed",g_gu2_IsZoomed}, \
    {"__gu2_MessageBeep",g_gu2_MessageBeep}, \
    {"__gu2_OpenClipboard",g_gu2_OpenClipboard}, \
    {"__gu2_ReleaseDC",g_gu2_ReleaseDC}, \
    {"__gu2_RemoveMenu",g_gu2_RemoveMenu}, \
    {"__gu2_ScreenToClient",g_gu2_ScreenToClient}, \
    {"__gu2_SetClipboardData",g_gu2_SetClipboardData}, \
    {"__gu2_SetFocus",g_gu2_SetFocus}, \
    {"__gu2_DrawMenuBar",g_gu2_DrawMenuBar}, \
    {"__gu2_SetMenu",g_gu2_SetMenu}, \
    {"__gu2_GetMenu",g_gu2_GetMenu}, \
    {"__gu2_WinHelpA",g_gu2_WinHelpA}, \
    {"__gd2_CreateFontIndirectA",g_gd2_CreateFontIndirectA}, \
    {"__gd2_ExtTextOutA",g_gd2_ExtTextOutA}, \
    {"__gd2_GetCharWidthA",g_gd2_GetCharWidthA}, \
    {"__gd2_GetObjectA",g_gd2_GetObjectA}, \
    {"__gd2_GetTextAlign",g_gd2_GetTextAlign}, \
    {"__gd2_GetTextExtentPoint32A",g_gd2_GetTextExtentPoint32A}, \
    {"__gd2_GetTextExtentPointA",g_gd2_GetTextExtentPointA}, \
    {"__gd2_SetTextAlign",g_gd2_SetTextAlign}, \
    /* end */

